config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')), # new
    path('', include('django.contrib.auth.urls')),
#    path('', TemplateView.as_view(template_name='index.html'), name='home'),
]

accounts/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator




class Company(models.Model):
    name = models.CharField(max_length=1000)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="company")

class financial_year(models.Model):
    year = models.CharField(max_length=1000)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="financial_year")
    

class fyauth(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    year = models.ForeignKey(financial_year,on_delete=models.CASCADE)

class cauth(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    company = models.ForeignKey(Company,on_delete=models.CASCADE)
    


# Create your models here.

class Warehouse(models.Model):
    name = models.CharField(max_length=200, unique=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Warehouse")

class Stock(models.Model):
    Model = models.CharField(max_length=100)
    Quantity = models.IntegerField(validators = [MinValueValidator(0)])
    Size = models.CharField(max_length=100)
    Name = models.CharField(max_length=100)
    Price = models.IntegerField()
    Color = models.CharField(max_length=200)
    Warehouse =  models.ForeignKey(Warehouse, on_delete=models.CASCADE, to_field='id', default='1')
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Stock")


        

    
#Multi Group--------------------------------------------------------------


class default_group(models.Model):
    Type_Choices = (("Capital Account","Capital Account"),("Loans(Liability)","Loans(Liability)"),("Current Liabilities","Current Liabilities"),("Fixed Assets","Fixed Assets"),("Investments","Investments"),("Current Assets","Current Assets"),("Branch Divisions","Branch Divisions"),("Suspense AC","Suspense AC"),("Sales Account","Sales Account"),("Purchase Accounts","Purchase Accounts"),("Direct Incomes","Direct Incomes"),("Direct Expenses","Direct Expenses"),("Indirect Incomes","Indirect Incomes"),("Indirect Expenses","Indirect Expenses"))
    df = models.BooleanField()
    type = models.CharField(max_length=100, choices=Type_Choices,default =Type_Choices[0])
    name = models.CharField(max_length=2000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)



class Ledger(models.Model):
    name = models.CharField(max_length = 100)
    df = models.BooleanField()
    cc = models.BooleanField()
    header = models.ForeignKey(default_group, on_delete=models.CASCADE, related_name="Ledger")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Ledger")
    
    

class Cost_Center(models.Model):
    Name = models.CharField(max_length = 100)
    df = models.BooleanField()
    Description = models.CharField(max_length=50000)
    ltype = models.ForeignKey(Ledger, on_delete= models.CASCADE, related_name="Cost_Center")
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Cost_Center")

#Group---------------------------------------------------------------------

class Order(models.Model):
    Model = models.CharField(max_length=200)
    Quantity = models.IntegerField()
    Size = models.CharField(max_length=100)
    Name = models.CharField(max_length=100)
    Price = models.IntegerField()
    Color = models.CharField(max_length=200)
    Warehouse =  models.CharField(max_length=200)
    stock_id = models.IntegerField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Order")
    fy = models.ForeignKey(financial_year, on_delete=models.CASCADE, related_name="Order")
    
    

class Invoice(models.Model):
    final = models.BooleanField()
    amount = models.IntegerField()
    Date  = models.DateField()
    Type_Choices = (("Cash","Cash"),("Credit Bill","Credit Bill"),("Goods Return","Goods Return"))
    name = models.CharField(max_length=1000)
    Cost_Center = models.ForeignKey(Cost_Center,on_delete=models.CASCADE, to_field='id', related_name="Invoices" )
    Orders = models.ManyToManyField(Order, related_name="Invoice" )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Invoice")
    fy = models.ForeignKey(financial_year, on_delete=models.CASCADE, related_name="Invoice")
    numberoforders = models.IntegerField(default = 0)
    Itype = models.CharField(max_length=100, choices=Type_Choices,default =Type_Choices[0] )
    def orders(self):
        return ', '.join([a.Name for a in self.Orders.all()])

class Receipt(models.Model):
    Cost_Center = models.ForeignKey(Cost_Center, on_delete=models.CASCADE, related_name="Receipt")
    money_account = models.ForeignKey('Cost_Center' ,on_delete=models.CASCADE, related_name="Receipt_money_account")
    Date  = models.DateField()
    Amount = models.IntegerField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Receipt")
    fy = models.ForeignKey(financial_year, on_delete=models.CASCADE, related_name="Receipt")
    

class Purchase(models.Model):
    Cost_Center = models.ForeignKey(Cost_Center, on_delete=models.CASCADE, related_name="Purchase")
    money_account = models.ForeignKey('Cost_Center', on_delete=models.CASCADE, related_name="Purchase_money_account")
    Date  = models.DateField()
    Amount = models.IntegerField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="Purchase")
    fy = models.ForeignKey(financial_year, on_delete=models.CASCADE, related_name="Purchase")

    
class dlsheet(models.Model):
    Date  = models.DateField()
    Receipts = models.ManyToManyField(Receipt)
    Purchases = models.ManyToManyField(Purchase)
    Invoices = models.ManyToManyField(Invoice)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name="dlsheet")
    fy = models.ForeignKey(financial_year, on_delete=models.CASCADE, related_name="dlsheet")

templates/ledger/addcategory.html
 <!-- ============================================================== -->
 {% extends 'base.html' %}
{% load static %}
{% block content %}  
 <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Ledgers</h3>
          
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                    
                    
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add Ledger</h4>
                        {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        
                        </ul>
                        {% endif %}
                        <form action="{% url 'addledgers' %}" method="post">
                             {% csrf_token %}
                             <label for="id_name">Name:</label>
                             {{ form.name }}
                             
                             <br>
                             <label for="id_header">Group:</label>
                             {{ form.header }}
                             
                            <br>
                            <label for="id_cc">Cost Center:</label>
                             <input type="checkbox" name="cc" id="id_cc">
                             <label for="id_cc">&nbsp;</label>
                             <br>
                         <button type="submit" value='save' name='save'>Add</button>
                         
                       </form>
                 
                    </div>
                </div>

            </div>
        </div>
        <!-- Row -->
       
        <!-- Row -->
        <!-- Row -->
      
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <footer class="footer"> © 2021 Flower Apps </footer>
        <!-- ============================================================== -->
    </div>
</div>


    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
{% endblock %}

templates/ledger/category.html
 <!-- ============================================================== -->
 {% extends 'base.html' %}
{% load static %}
{% block content %}  
 <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Ledgers</h3>
          
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                   
                    <div class="d-flex m-r-20 m-l-10 hidden-md-down">
                        <a style='color: white;' type="button" class="btn waves-effect waves-light btn-success" href="{% url 'addledgers' %}">Add</a>
                        
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Ledger Data</h4>
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                 <tr>
                                   
                                    
                                       <th style='text-transform: uppercase;'>Name</th>
                                       <th style='text-transform: uppercase;'>Group</th>
                                  
                                        
                                 </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                 
                                        
                                           <th style='text-transform: uppercase;'>Name</th>
                                           <th style='text-transform: uppercase;'>Group</th>
                                      
                                          
    
                                     </tr>
                                </tfoot>
                                <tbody>

                                    {% for item in stock %}
                                    <tr>
                             
                                        <td><a href='/ledgers/edit/{{ item.id }}/'>{{ item.name }}</a></td>
                                        <td>{{ item.header.name }}</a></td>

                                       
                                  
                                    
                                    </tr>
                                        {% endfor %}
                                </tbody>
                            </table>
                        </div>
                       




                    </div>
                </div>
          
               
            </div>
        </div>
        <!-- Row -->
       
        <!-- Row -->
        <!-- Row -->
      
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <footer class="footer"> © 2021 Flower Apps </footer>
        <!-- ============================================================== -->
    </div>
</div>


    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
{% endblock %}

templates/ledger/editcategory.html



 <!-- ============================================================== -->
 {% extends 'base.html' %}
{% load static %}
{% block content %}  
 <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Ledger</h3>
          
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                    
                    
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                    <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text- ">Edit Ledger</h6>
                      
                    </div>
                    <div class="card-body">
                        {% if messages %}
                             <ul class="messages">
                             {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                             {% endfor %}
                             
                             </ul>
                             {% endif %}
                             <form action="{% url 'editledgers' stockid=form.instance.pk %}" method="post">
                                {% csrf_token %}
                                {{ form.as_p }}
                           
                              <button type="submit" value='save' name='save'>Save</button>
                              <input type="submit" name="save" value="delete" onclick="return confirm('Do you really want to delete the stock?');" />
                              
                            </form>                        
                    </div>
                </div>
                
          
               
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card shadow mb-4">
                  
                    <div class="card-body">
                        <h2 class="m-0 font-weight-bold text- ">Cost Centers</h2>
                        <div class="table-responsive m-t-40">
                            <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                 <tr>
                                   
                                    
                                       <th style='text-transform: uppercase;'>Name</th>
                                       <th style='text-transform: uppercase;'>Description</th>
                                       <th style='text-transform: uppercase;'>Under</th>
                                  
                                        
                                 </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                 
                                        
                                           <th style='text-transform: uppercase;'>Name</th>
                                           <th style='text-transform: uppercase;'>Description</th>
                                           <th style='text-transform: uppercase;'>Under</th>
                                      
                                          
    
                                     </tr>
                                </tfoot>
                                <tbody>

                                    {% for item in stock %}
                                    <tr>
                             
                                        <td><a href='/costcenters/edit/{{ item.id }}/'>{{ item.Name }}</a></td>
                                        <td>{{ item.Description }}</td>
                                        <td>{{ item.ltype.name }}</td>
                        
                                  
                                    
                                    </tr>
                                        {% endfor %}
                                </tbody>
                            </table>
                        </div>
                              
                            </form>                        
                    </div>
                </div>
                
          
               
            </div>
        </div>
        <!-- Row -->
       
        <!-- Row -->
        <!-- Row -->
      
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <footer class="footer"> © 2021 Flower Apps </footer>
        <!-- ============================================================== -->
    </div>
</div>


    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
{% endblock %}

templates/ledger/lselector.html
 <!-- ============================================================== -->
 {% extends 'base.html' %}
{% load static %}
{% block content %}  
 <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Accounting Vouchers</h3>
          
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                    
                    
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add</h4>
                        {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        
                        </ul>
                        {% endif %}
                        <form action="{% url 'addreceipt' %}" method="post">
                             {% csrf_token %}
                             {{ form.as_p }}
                         <button type="submit" value='save' name='save'>Add</button>
                         
                       </form>
                 
                    </div>
                </div>

            </div>
        </div>
        <!-- Row -->
       
        <!-- Row -->
        <!-- Row -->
      
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <footer class="footer"> © 2021 Flower Apps </footer>
        <!-- ============================================================== -->
    </div>
</div>


    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
{% endblock %}

templates/ledger/plselector.html
 <!-- ============================================================== -->
 {% extends 'base.html' %}
{% load static %}
{% block content %}  
 <div class="page-wrapper">
    <!-- ============================================================== -->
    <!-- Container fluid  -->
    <!-- ============================================================== -->
    <div class="container-fluid">
        <!-- ============================================================== -->
        <!-- Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <div class="row page-titles">
            <div class="col-md-5 col-8 align-self-center">
                <h3 class="text-themecolor">Accounting Vouchers</h3>
          
            </div>
            <div class="col-md-7 col-4 align-self-center">
                <div class="d-flex m-t-10 justify-content-end">
                    
                    
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- End Bread crumb and right sidebar toggle -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Start Page Content -->
        <!-- ============================================================== -->
        <!-- Row -->
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Add</h4>
                        {% if messages %}
                        <ul class="messages">
                        {% for message in messages %}
                               <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                        
                        </ul>
                        {% endif %}
                        <form action="{% url 'addpurchase' %}" method="post">
                             {% csrf_token %}
                             {{ form.as_p }}
                         <button type="submit" value='save' name='save'>Add</button>
                         
                       </form>
                 
                    </div>
                </div>

            </div>
        </div>
        <!-- Row -->
       
        <!-- Row -->
        <!-- Row -->
      
        <!-- ============================================================== -->
        <!-- End PAge Content -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right sidebar -->
        <!-- ============================================================== -->
        <!-- .right-sidebar -->
        <footer class="footer"> © 2021 Flower Apps </footer>
        <!-- ============================================================== -->
    </div>
</div>


    <!-- ============================================================== -->
    <!-- End Container fluid  -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- footer -->
    <!-- ============================================================== -->
{% endblock %}